name=['Tommy','Livia','Lisa','Peter']
print("You are my best friend, would you like to have dinner with me, "+name[0]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[1]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[2]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[3]+" ?")
print("Tommy can't come. ")
print("Sad to hear that, "+name[0]+" .")
print("Tommy can't come, "+name[1]+" .")
print("Tommy can't come, "+name[2]+" .")
print("Tommy can't come, "+name[3]+" .")
name[0] = "Jenny"
print("You are my best friend, would you like to have dinner with me, "+name[0]+" ?")
name.append("Tom")
name.insert(0, "Jerry")
name.insert(2, "Billy")
print("You are my best friend, would you like to have dinner with me, "+name[0]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[1]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[2]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[3]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[4]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[5]+" ?")
print("You are my best friend, would you like to have dinner with me, "+name[6]+" ?")

